<?php
/**
 * Exports Actions
 *
 * These are actions related to exporting data from KBS.
 *
 * @package     KBS
 * @subpackage  Admin/Export
 * @copyright   Copyright (c) 2016, Mike Howard
 * @since       1.1
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 */
if ( ! defined( 'ABSPATH' ) )
	exit;

/**
 * Process the download file generated by a batch export
 *
 * @since	1.1
 * @return	void
 */
function kbs_process_batch_export_download() {

    if ( ! isset( $_REQUEST['kbs-action'] ) || 'download_batch_export' !== $_REQUEST['kbs-action'] )    {
        return;
    }

	if ( ! wp_verify_nonce( $_REQUEST['nonce'], 'kbs-batch-export' ) ) {
		wp_die( __( 'Nonce verification failed', 'kb-support' ), __( 'Error', 'kb-support' ), array( 'response' => 403 ) );
	}

	require_once( KBS_PLUGIN_DIR . '/includes/admin/import_export/export/class-batch-export.php' );

	do_action( 'kbs_batch_export_class_include', $_REQUEST['class'] );

	$export = new $_REQUEST['class'];
	$export->export();

} // kbs_process_batch_export_download
add_action( 'init', 'kbs_process_batch_export_download' );

/*------------------------------
 * SETTINGS
 *----------------------------*/
/**
 * Process a settings export that generates a .json file of the shop settings
 *
 * @since       1.1
 * @return      void
 */
function kbs_tools_settings_process_export() {

    if ( ! isset( $_POST['kbs-action'] ) || 'export_settings' != $_POST['kbs-action'] )	{
		return;
	}

	if ( empty( $_POST['kbs_export_nonce'] ) )    {
		return;
    }

	if ( ! wp_verify_nonce( $_POST['kbs_export_nonce'], 'kbs_export_nonce' ) )    {
		return;
    }

	if ( ! current_user_can( 'export_ticket_reports' ) ) {
		return;
    }

	$settings = array();
	$settings = get_option( 'kbs_settings' );

	ignore_user_abort( true );

	if ( ! kbs_is_func_disabled( 'set_time_limit' ) )
		set_time_limit( 0 );

	nocache_headers();
	header( 'Content-Type: application/json; charset=utf-8' );
	header( 'Content-Disposition: attachment; filename=' . apply_filters( 'kbs_settings_export_filename', 'kbs-settings-export-' . date( 'd-m-Y' ) ) . '.json' );
	header( "Expires: 0" );

	echo json_encode( $settings );
	exit;
} // kbs_tools_settings_process_export
add_action( 'init', 'kbs_tools_settings_process_export' );

/**
 * Process a settings import from a json file
 *
 * @since   1.1
 * @return  void
 */
function kbs_tools_settings_process_import() {

    if ( ! isset( $_POST['kbs-action'] ) || 'import_settings' != $_POST['kbs-action'] )	{
		return;
	}

	if ( empty( $_POST['kbs_import_nonce'] ) ) {
		return;
    }

	if ( ! wp_verify_nonce( $_POST['kbs_import_nonce'], 'kbs_import_nonce' ) )   {
		return;
    }

	if ( ! current_user_can( 'export_ticket_reports' ) ) {
		return;
    }

	if ( kbs_get_file_extension( $_FILES['import_file']['name'] ) != 'json' ) {
		wp_safe_redirect( add_query_arg( array(
            'post_type'    => 'kbs_ticket',
            'page'         => 'kbs-tools',
            'tab'          => 'import',
            'kbs-message'  => 'settings-import-missing-file'
        ), admin_url( 'edit.php' ) ) );
        exit;
	}

	$import_file = $_FILES['import_file']['tmp_name'];

	if ( empty( $import_file ) ) {
		wp_safe_redirect( add_query_arg( array(
            'post_type'    => 'kbs_ticket',
            'page'         => 'kbs-tools',
            'tab'          => 'import',
            'kbs-message'  => 'settings-import-missing-file'
        ), admin_url( 'edit.php' ) ) );
        exit;
	}

	// Retrieve the settings from the file and convert the json object to an array
	$settings = kbs_object_to_array( json_decode( file_get_contents( $import_file ) ) );

	update_option( 'kbs_settings', $settings );

	wp_safe_redirect( add_query_arg( array(
		'post_type'    => 'kbs_ticket',
		'page'         => 'kbs-tools',
		'tab'          => 'import',
		'kbs-message'  => 'settings-imported'
	), admin_url( 'edit.php' ) ) );
	exit;

} // kbs_tools_settings_process_import
add_action( 'init', 'kbs_tools_settings_process_import' );

/**
 * Export all the clients to a CSV file.
 *
 * Note: The WordPress Database API is being used directly for performance
 * reasons (workaround of calling all posts and fetch data respectively)
 *
 * @since	1.1
 * @return	void
 */
function mdjm_export_all_clients() {
	require_once MDJM_PLUGIN_DIR . '/includes/admin/reporting/class-mdjm-clients-export.php';

	$client_export = new MDJM_Clients_Export();

	$client_export->export();
} // mdjm_export_all_clients
add_action( 'mdjm_email_export', 'mdjm_export_all_clients' );

/**
 * Add a hook allowing extensions to register a hook on the batch export process
 *
 * @since	1.1
 * @return	void
 */
function kbs_register_batch_exporters() {
	if ( is_admin() ) {
		do_action( 'kbs_register_batch_exporter' );
	}
} // kbs_register_batch_exporters
add_action( 'plugins_loaded', 'kbs_register_batch_exporters' );

/**
 * Register the events batch exporter
 * @since	1.1
 */
function kbs_register_tickets_batch_export() {
	add_action( 'kbs_batch_export_class_include', 'kbs_include_tickets_batch_processer', 10, 1 );
} // kbs_register_tickets_batch_export
add_action( 'kbs_register_batch_exporter', 'kbs_register_tickets_batch_export', 10 );

/**
 * Loads the tickets batch process if needed
 *
 * @since 	1.1
 * @param	str		$class	The class being requested to run for the batch export
 * @return	void
 */
function kbs_include_tickets_batch_processer( $class ) {

	if ( 'KBS_Batch_Export_Tickets' === $class ) {
		require_once( KBS_PLUGIN_DIR . '/includes/admin/import_export/export/class-batch-export-tickets.php' );
	}

} // kbs_include_tickets_batch_processer
